language: objective-c
osx_image: xcode9.2
env:
  - XCODE_SCHEME=VKarmaneSDK-Example
    XCODE_WORKSPACE=Example/VKarmaneSDK.xcworkspace
    XCODE_DESTINATION="platform=iOS Simulator,OS=10.0,name=iPhone 5s"
script:
  - xcodebuild clean -project "$XCODE_PROJECT"
  - set -o pipefail && xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -destination "$XCODE_DESTINATION" | xcpretty -s
  - pod lib lint
